development:
  adapter: sqlite3
  encoding: unicode
  database: edifly
  pool: 5
  username: postgres
  password: 12345678

test:
  adapter: sqlite3
  encoding: unicode
  database: edifly-test
  pool: 5
  username: postgres
  password: 12345678