default: &default 
  adapter: sqlite3

development:
  <<: *default 
  database: db/edifly-server.sqlite3

test:
  <<: *default 
  database: db/edifly-server.sqlite3

production:
  <<: *default 
  database: ~/edifly-server/shared/db/production.sqlite3